[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirects (optional): ensure clean URLs
[[redirects]]
  from = "/tools"
  to = "/tools/"
  status = 301



[[redirects]]
  from = "https://wheelspicker.com/*"
  to = "https://spinnawheel.com/:splat"
  status = 301
  force = true

